### ISSUE TITLE
Please add LICENSE to repository

### ISSUE THREAD

**Issue by ghost** [jjpe/tempus_fugit#1]
Hi, thank you for this crate, I would really appreciate it, if you could add a LICENSE file to your repository.

**Comment by jjpe** [comment]
I just released v0.9.0, which is dual-licensed under the MIT and Apache 2.0 licenses.
The license files are also included.

**Comment by ghost** [comment]
Thank you, btw awesome crate name!

**Comment by jjpe** [comment]
I'm glad you like it. Enjoy!
